swagger: '2.0'
info:
  description: >
    This is the RESTful API for a user to manage his/her pending approvals in WSO2 Identity Server. This API can be used to
    retrieve pending approvals and update the status of the approval tasks for the authenticated user.
  version: "v1"
  title: WSO2 Identity Server - Workflow Approval API Definition (Removed from API)
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management/"
    email: "architecture@wso2.org"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

schemes:
 - https

# Tags are used for organizing operations.
tags:
- name: me
  description: Operations for the authenticated user.

paths:
  /me/approval-tasks:
    get:
      tags:
        - me
      summary: Removed from API
      operationId: listApprovalTasksForLoggedInUser
      description: >
        Retrieve the available approval tasks in the system for the authenticated user. 
        (Removed from API)
      responses:
        '410':
          description: Gone

  /me/approval-tasks/{task-id}:
    get:
      tags:
        - me
      summary: Removed from API
      operationId: getApprovalTaskInfo
      description: >
        Retrieves information of a specific approval task identified by the task(Removed from API)
      parameters:
        - $ref: '#/parameters/taskIdPathParam'
      responses:
        '410':
          description: Gone

  /me/approval-tasks/{task-id}/state:
    put:
      tags:
        - me
      summary: Removed from API
      operationId: updateStateOfTask
      description: |
        Update the approval task status
        (Removed from API)
      parameters:
        - $ref: '#/parameters/taskIdPathParam'
      responses:
        '410':
          description: Gone

parameters:
    taskIdPathParam:
      in: path
      name: task-id
      required: true
      type: string
      description: Task ID


host: localhost:9443
basePath: /t/{tenant-domain}/api/users/v1
